language: python
python:
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

# Install the codecov pip dependency
install:
  - pip install -r requirements.txt

# Run the unit test
script:
  - export PATHONPATH=`pwd`
  - coverage run --timid --branch --source fe,be --concurrency=thread -m pytest -v --ignore=fe/data
